server:
  forward-headers-strategy: native

proxy:
  title: Anomanor Shinyproxy
  logo-url: https://menne-biomed.de/images/mennebiomed48.gif
  container-log-path: ./shinyproxy-logs
  container-wait-time: 10000
  port: 8080
  heartbeat-timeout: 60000
  authentication: openid # tested ok with 'simple'
  admin-groups: admins
  landing-page: /app_direct/anomanor
  # Only used for testing with authentication simple
  users:
  - name: jack
    password: ps
    groups: admins
  oauth2:
    resource-id: shinyproxy
    jwks-url: https://keycloak.hrmconsensus.org/realms/anomanor/protocol/openid-connect/certs
    roles-claim: realm_roles
    username-attribute: preferred_username
  openid:
    # https://github.com/openanalytics/shinyproxy-config-examples/tree/master/12-openid-keycloak
    auth-url: https://keycloak.hrmconsensus.org/realms/anomanor/protocol/openid-connect/auth
    token-url: https://keycloak.hrmconsensus.org/realms/anomanor/protocol/openid-connect/token
    jwks-url: https://keycloak.hrmconsensus.org/realms/anomanor/protocol/openid-connect/certs
    client-id: anomanor
    client-secret: ${ANOMANOR_SECRET}
    username-attribute: preferred_username
    logout-url: /logout-success

  docker:
      internal-networking: true
  specs:
  # Only for testing. Requires openanalytics/shinyproxy-demo
  - id: 01_hello
    display-name: Hello Application
    description: Application which demonstrates the basics of a Shiny app
    container-cmd: ["R", "-e", "shinyproxy::run_01_hello()"]
    container-image: openanalytics/shinyproxy-demo
    container-network: anomanor-net

  - id: anomanor
    display-name: Anomanor with Keycloak
    container-cmd: ["R", "-e", "anomanor::run_app()"]
    #container-cmd: ["bash"]
    container-volumes: [
      "/home/hrmconsensus/anomanor_data/anomanor/:${ANOMANOR_DATA}/"
      ]
    container-image: anomanor
    container-network: anomanor-net
    seats-per-container: 2
    minimum-seats-available: 2


logging:
  requestdump: false