FROM quay.io/keycloak/keycloak:24.0.5
# docker build -f Dockerfile_keycloak .
ENV KEYCLOAK_USER=${MASTER_ADMIN_USERNAME:-admin}
ENV KEYCLOAK_PASSWORD=${MASTER_ADMIN_PASSWORD:-admin}
ENV KC_DB=postgres
# https://stackoverflow.com/questions/75082054/keycloak-does-not-use-postgres-database-and-tries-to-connect-h2-database
COPY ./inst/anomanortheme /opt/keycloak/themes/anomanortheme
WORKDIR /opt/keycloak
RUN /opt/keycloak/bin/kc.sh build
ENTRYPOINT ["/opt/keycloak/bin/kc.sh"]
