FROM openanalytics/shinyproxy:3.1.1

# https://vsupalov.com/docker-arg-env-variable-guide/
# ARG: Build time variables from .ENV
ARG KEYCLOAK_IP
ARG ANOMANOR_DATA
ARG ANOMANOR_SECRET

# ENV: run time variables
ENV KEYCLOAK_IP=${KEYCLOAK_IP}
ENV ANOMANOR_DATA=${ANOMANOR_DATA}
ENV ANOMANOR_SECRET=${ANOMANOR_SECRET}
COPY application.yml /opt/shinyproxy/application.yml
