# Active configuration set by environment variable, e.g.
# Sys.setenv("R_CONFIG_ACTIVE" = "keycloak_devel") in file .Renviron
default:
  # All directories are relative to anomanor_data_base
  anomanor_data_base: !expr Sys.getenv("ANOMANOR_DATA")
  cache_dir: cache
  data_dir: data
  database_dir : db
  use_keycloak: FALSE
  force_console: FALSE
  show_testbuttons: TRUE
  keycloak_port: 8010
  keycloak_site: !expr Sys.getenv("KEYCLOAK_SITE")
  keycloak_realm: anomanor
  show_results_to_experts: TRUE
  complete_experts_ratings: TRUE
  test_email_url: !expr Sys.getenv("TEST_EMAIL_URL")

sa_trainee:
  app_user: caesar
  app_groups: trainees

sa_admin:
  app_user: anton
  app_groups: admins
  complete_experts_ratings: FALSE

sa_expert:
  app_user: x_bertha
  app_groups: experts

sa_consensus:
  app_user: x_consensus
  app_groups: experts

sa_random_trainee:
  app_user: random # Replaced by random name
  app_groups: trainee

test:
  # email_url only to generate sample data
  anomanor_data_base: !expr anomanor::test_database_dir()
  #anomanor_data_base: !expr tempdir(TRUE)
  test_email_url: !expr Sys.getenv("TEST_EMAIL_URL")
  app_user: test
  app_groups: trainees

test_expert:
  inherits: test
  app_user: x_anton
  app_groups: experts

# Asssume Keycloak server is running
# Only for inheritance, do not use directly
keycloak:
  use_keycloak: TRUE
  anomanor_admin_username: !expr Sys.getenv("ANOMANOR_ADMIN_USERNAME")
  anomanor_admin_password: !expr Sys.getenv("ANOMANOR_ADMIN_PASSWORD")
  anomanor_secret: !expr Sys.getenv("ANOMANOR_SECRET")


keycloak_devel:
  inherits: keycloak
  use_keycloak: FALSE
  # app_user only for testing without keycloak
  app_user: anton
  app_groups: admins

keycloak_production:
  inherits: keycloak
  use_keycloak: TRUE
  # Make show_testbuttons FALSE in final
  show_testbuttons: FALSE
  #keycloak_port: 443 # https is set automatically

keycloak_test: # Only for testing remote keycloak in notest_keycloak.R
  # Uses ANOMANOR_xxx from Renviron_keycloak_test
  inherits: keycloak
  use_keycloak: TRUE

