---
title: Disorder of the rectoanal inhibitory reflex
output: github_document
editor_options: 
  markdown: 
    wrap: 72
---

# About

This interactive application provides online training for physicians and
other practitioners using high-resolution anorectal manometry and the
[London
Classification](https://onlinelibrary.wiley.com/doi/full/10.1111/nmo.13679)
for disorders of anorectal function. It provides the opportunity to
compare performance against a "reference standard" set by the lead
authors of this classification system. Data acquired during this
training will be used to assess inter-observer agreement between
practitioners.

The results will be published. All those completing all cases will be
acknowledged. This information will also inform the development of
version 2.0 of the London classification.

* Version: `r packageVersion("anomanor")`
```{r, echo = FALSE, results = 'asis'}
desc::description$new()$get_authors() |> 
purrr::walk(
  \(x) {
   cat("* ",x$given, x$family, "(") 
   cat( x$role, sep = ", ")
   cat(")\n")
  }
) 

```

_aut, cre, cph, ..._ see [Library of Congress Code List for Relators](https://www.loc.gov/marc/relators/relaterm.html) 
