# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

encode32 <- function(hash_int, length = 7L) {
    .Call(`_anomanor_encode32`, hash_int, length)
}

rev_limit <- function(x, min, max) {
    .Call(`_anomanor_rev_limit`, x, min, max)
}

